import argparse


def initConfig():
    args = argparse.ArgumentParser()
    args.add_argument('--seed', type=int, default=11)
    args.add_argument('--dataset', type=str, default='BBN', choices=['BBN', 'OntoNotes', 'FewNerd'])
    args.add_argument('--device', type=int, default=0)
    args.add_argument('--n_gpu', type=int, default=1)
    args.add_argument('--pretrain_path', type=str, default=None)
    args.add_argument('--contra_type', type=str, default='sup', choices=['sup', 'self', 'test'])
    args.add_argument('--combine_type', type=str, default='tot', choices=['tot', 'ce', 'sup', 'mlm', 'None'])
    args.add_argument('--cluster_type', type=str, default='HAC', choices=['HAC', 'HDBSCAN', 'FINCH'])
    args.add_argument('--cluster_method', type=str, default='average',
                      choices=['single', 'complete', 'average', 'weighted', 'centroid', 'median', 'ward'])
    args.add_argument('--train_type', type=str, default='train', choices=['pretrain', 'train'])
    args.add_argument('--cluster_rep', type=str, default='vec', choices=['vec', 'box'])
    args.add_argument('--cluster2box', type=str, default='CR_g', choices=['R2B', 'CR_g', 'CR_a', 'R2B2', 'R2B3'])

    args.add_argument('--margin', type=float, default=24)
    args.add_argument('--alpha', type=float, default=0.2)
    args.add_argument('--enable_weight', type=int, default=1, choices=[0, 1])
    args.add_argument('--dist_type', type=str, default='BoxE', choices=['BoxE', 'Q2B'])
    args.add_argument('--box_loss_type', type=str, default='neg_sample', choices=['neg_sample', 'margin_base'])
    args.add_argument('--box_self_adv', type=int, default=1, choices=[0, 1])
    args.add_argument('--adv_temp', type=float, default=8.0)
    args.add_argument('--mini_ins_size', type=float, default=0.1)
    args.add_argument('--mini_type_size', type=float, default=0.1)
    args.add_argument('--inter_n_neg', type=int, default=10)
    args.add_argument('--type_n_neg', type=int, default=10)
    args.add_argument('--cross_n_neg', type=int, default=10)
    args.add_argument('--gumbel_beta', type=float, default=0.00036026463511690845)
    args.add_argument('--tanh', type=int, default=0, choices=[0, 1])
    args.add_argument('--n_layer', type=int, default=2)
    args.add_argument('--pbl_ratio', type=float, default=0.5)
    args.add_argument('--enable_pbl_ratio', type=int, default=0, choices=[0, 1])
    args.add_argument('--gen_box_method', type=str, default='B4T', choices=['B4T', 'mlp'])
    args.add_argument('--type_box_dim', type=int, default=768)
    args.add_argument('--enable_box_inter', type=int, default=1, choices=[0, 1])
    args.add_argument('--enable_type_inter', type=int, default=0, choices=[0, 1])
    args.add_argument('--inter_type', type=str, default='BCE', choices=['BCE', 'BPR'])
    args.add_argument('--box_inter_type', type=str, default='box+', choices=['B4T', 'taxo', 'box+', 'IoU'])
    args.add_argument('--box_taxo_margin', type=float, default=0.01)
    args.add_argument('--box_taxo_eps', type=float, default=-0.03)
    args.add_argument('--box_taxo_alpha', type=float, default=1)
    args.add_argument('--box_taxo_extra', type=float, default=0.1)
    args.add_argument('--box_inter_start', type=int, default=-1)
    args.add_argument('--cross_inter_start', type=int, default=-1)
    args.add_argument('--IoU_margin', type=float, default=2)
    args.add_argument('--d_alpha', type=float, default=1.0)
    args.add_argument('--IoU_mode', type=str, default='margin', choices=['margin', 'BPR'])
    args.add_argument('--type_inter_type', type=str, default='box+', choices=['B4T', 'taxo', 'box+', 'IoU', 'cbox'])
    args.add_argument('--type_taxo_margin', type=float, default=0.01)
    args.add_argument('--type_taxo_eps', type=float, default=-0.03)
    args.add_argument('--type_taxo_alpha', type=float, default=1)
    args.add_argument('--type_taxo_extra', type=float, default=0.1)
    args.add_argument('--enable_cross_inter', type=int, default=0, choices=[0, 1])
    args.add_argument('--enable_cross_pb', type=int, default=0, choices=[0, 1])
    args.add_argument('--dynomic_pb_margin', type=int, default=0, choices=[0, 1])
    args.add_argument('--cross_inter_type', type=str, default='box+',
                      choices=['B4T', 'taxo', 'box+', 'IoU', 'dist', 'cbox'])
    args.add_argument('--cross_taxo_margin', type=float, default=0.01)
    args.add_argument('--cross_taxo_eps', type=float, default=-0.03)
    args.add_argument('--cross_taxo_alpha', type=float, default=1)
    args.add_argument('--cross_taxo_extra', type=float, default=0.1)
    args.add_argument('--proj_ins2type', type=int, default=0, choices=[0, 1])
    args.add_argument('--proj_type2ins', type=int, default=0, choices=[0, 1])
    args.add_argument('--type_IoU_margin', type=float, default=2)
    args.add_argument('--type_d_alpha', type=float, default=1.0)
    args.add_argument('--type_IoU_mode', type=str, default='margin', choices=['margin', 'BPR'])
    args.add_argument('--cross_IoU_margin', type=float, default=2)
    args.add_argument('--cross_d_alpha', type=float, default=1.0)
    args.add_argument('--cross_IoU_mode', type=str, default='margin', choices=['margin', 'BPR'])
    args.add_argument('--match_weight', type=int, default=0, choices=[0, 1])
    args.add_argument('--cross_weight', type=float, default=1)
    args.add_argument('--cross_dynamic_weight', type=int, default=0, choices=[0, 1])  # 总损失里的动态权重
    args.add_argument('--onlyBottom', type=int, default=0, choices=[0, 1])
    args.add_argument('--cross_self_adv', type=int, default=0, choices=[0, 1])
    args.add_argument('--cross_adv_temp', type=float, default=10)
    args.add_argument('--cross_dist_margin', type=float, default=24)

    args.add_argument('--enable_type_desc', type=int, default=0, choices=[0, 1])
    args.add_argument('--use_type_emb', type=int, default=0, choices=[0, 1])
    args.add_argument('--init_cen_span', type=float, default=0.01)
    args.add_argument('--init_off_span', type=float, default=0.1)
    args.add_argument('--init_type', type=int, default=1, choices=[0, 1])
    args.add_argument('--type_emb_method', type=str, default='B4T', choices=['B4T', 'BoxE'])

    args.add_argument('--mode', type=str, default='train', choices=['train', 'test'])
    args.add_argument('--model', type=str, default='bert', choices=['bert'])
    args.add_argument('--model_type', type=str, default='bert-base-uncased', choices=['bert-base-uncased'])
    args.add_argument('--scheduler_type', type=str, default='linear', choices=['linear'])
    args.add_argument('--split_val', type=int, default=1, choices=[0, 1])
    args.add_argument('--val_ratio', type=float, default=0.2)
    args.add_argument('--view_strategy', type=str, default='rtr', choices=['rtr', 'none'])
    args.add_argument('--mask_prob', type=float, default=0.15)

    args.add_argument('--num_epoch', type=int, default=100)
    args.add_argument('--stop_epoch', type=int, default=-1)
    args.add_argument('--warmup_epoch', type=int, default=20)
    args.add_argument('--num_workers', type=int, default=4)
    args.add_argument('--mlm_batch_size', type=int, default=48)
    args.add_argument('--labeled_batch_size', type=int, default=48)
    args.add_argument('--self_batch_size', type=int, default=48)
    args.add_argument('--eval_batch_size', type=int, default=48)
    args.add_argument('--weight_decay', type=float, default=0.01)
    args.add_argument('--lr', type=float, default=2e-5)
    args.add_argument('--lr_box', type=float, default=1e-3)
    args.add_argument('--single_box_model', type=int, default=0)
    args.add_argument('--adam_epsilon', type=float, default=1e-6)

    args.add_argument('--mention_limit', type=int, default=100)
    args.add_argument('--input_limit', type=int, default=1000)
    args.add_argument('--do_lower', type=bool, default=False)

    args = args.parse_args()
    return args
